"""
Configuration file for the Coronavirus website scraper's main code
"""

# The main URL to fetch data from
URL = "https://www.worldometers.info/coronavirus/"

# The URL to fetch USA states data from
USA_URL = "https://www.worldometers.info/coronavirus/country/us/"

# Update time list - fetch data at the time items in the list
UPDATE_TIME = ['08:00:00', '16:00:00', '00:00:00']
# Countries to fetch - empty list: fetch all countries
COUNTRIES_FETCH = []

# Error message printed when failing to fetch data
ERR_MSG_FETCH = 'Failed to fetch data. Check HTML code and URL address'

# Error messages printed when failing to open a file and writing to a file
ERR_FILE_OPEN = 'Failed to open a file!'
ERR_FILE_WRITE = 'Failed to write to a file!'

# Args constants
REQUIRED_NUM_OF_ARGS = 3
ARG_UPDATES_FILE = 1
ARG_COUNTRIES_FILE = 2

# database personal variables:
USER_NAME = ''
PASSWORD = ''
HOST = ''

# API response
API = "https://api.covidtracking.com/v1/states/current.json"
OK_STATUS = 200

COUNTRIES_NAMES_TO_CODES = {
  "Afghanistan": "AFG",
  "Albania": "ALB",
  "Algeria": "DZA",
  "American Samoa": "ASM",
  "Andorra": "AND",
  "Angola": "AGO",
  "Anguilla": "AIA",
  "Antigua and Barbuda": "ATG",
  "Argentina": "ARG",
  "Armenia": "ARM",
  "Aruba": "ABW",
  "Australia": "AUS",
  "Austria": "AUT",
  "Azerbaijan": "AZE",
  "Bahrain": "BHR",
  "Bangladesh": "BGD",
  "Barbados": "BRB",
  "Belarus": "BLR",
  "Belgium": "BEL",
  "Belize": "BLZ",
  "Benin": "BEN",
  "Bermuda": "BMU",
  "Bhutan": "BTN",
  "Bolivia": "BOL",
  "Bonaire, Sint Eustatius and Saba": "BES",
  "Bosnia and Herzegovina": "BIH",
  "Botswana": "BWA",
  "Brazil": "BRA",
  "British Indian Ocean Territory": "IOT",
  "British Virgin Islands": "VGB",
  "Brunei Darussalam": "BRN",
  "Bulgaria": "BGR",
  "Burkina Faso": "BFA",
  "Myanmar": "MMR",
  "Burundi": "BDI",
  "Cambodia": "KHM",
  "Cameroon": "CMR",
  "Canada": "CAN",
  "Cabo Verde": "CPV",
  "Cayman Islands": "CYM",
  "Central African Republic": "CAF",
  "Chad": "TCD",
  "Chile": "CHL",
  "China": "CHN",
  "Colombia": "COL",
  "Comoros": "COM",
  "Cook Islands": "COK",
  "Costa Rica": "CRI",
  "Côte dIvoire": "CIV",
  "Croatia": "HRV",
  "Cuba": "CUB",
  "Curaçao": "CUW",
  "Cyprus": "CYP",
  "Czechia": "CZE",
  "Denmark": "DNK",
  "Djibouti": "DJI",
  "Dominica": "DMA",
  "Dominican Republic": "DOM",
  "Ecuador": "ECU",
  "Egypt": "EGY",
  "El Salvador": "SLV",
  "Equatorial Guinea": "GNQ",
  "Eritrea": "ERI",
  "Estonia": "EST",
  "Ethiopia": "ETH",
  "Falkland Islands": "FLK",
  "Faroe Islands": "FRO",
  "Federated States of Micronesia": "FSM",
  "Fiji": "FJI",
  "Finland": "FIN",
  "France": "FRA",
  "French Guiana": "GUF",
  "French Polynesia": "PYF",
  "Gabon": "GAB",
  "Georgia": "GEO",
  "Germany": "DEU",
  "Ghana": "GHA",
  "Gibraltar": "GIB",
  "Greece": "GRC",
  "Greenland": "GRL",
  "Grenada": "GRD",
  "Guadeloupe": "GLP",
  "Guam": "GUM",
  "Guatemala": "GTM",
  "Guinea": "GIN",
  "Guinea-Bissau": "GNB",
  "Guyana": "GUY",
  "Haiti": "HTI",
  "Honduras": "HND",
  "Hong Kong": "HKG",
  "Hungary": "HUN",
  "Iceland": "ISL",
  "India": "IND",
  "Indonesia": "IDN",
  "Iran": "IRN",
  "Iraq": "IRQ",
  "Ireland": "IRL",
  "Israel": "ISR",
  "Italy": "ITA",
  "Jamaica": "JAM",
  "Japan": "JPN",
  "Jordan": "JOR",
  "Kazakhstan": "KAZ",
  "Kenya": "KEN",
  "Kiribati": "KIR",
  "Kuwait": "KWT",
  "Kyrgyzstan": "KGZ",
  "Laos": "LAO",
  "Latvia": "LVA",
  "Lebanon": "LBN",
  "Lesotho": "LSO",
  "Liberia": "LBR",
  "Libya": "LBY",
  "Liechtenstein": "LIE",
  "Lithuania": "LTU",
  "Luxembourg": "LUX",
  "Macao": "MAC",
  "Macedonia": "MKD",
  "Madagascar": "MDG",
  "Malawi": "MWI",
  "Malaysia": "MYS",
  "Maldives": "MDV",
  "Mali": "MLI",
  "Malta": "MLT",
  "Marshall Islands": "MHL",
  "Martinique": "MTQ",
  "Mauritania": "MRT",
  "Mauritius": "MUS",
  "Mayotte": "MYT",
  "Mexico": "MEX",
  "Moldova": "MDA",
  "Monaco": "MCO",
  "Mongolia": "MNG",
  "Montenegro": "MNE",
  "Montserrat": "MSR",
  "Morocco": "MAR",
  "Mozambique": "MOZ",
  "Namibia": "NAM",
  "Nauru": "NRU",
  "Nepal": "NPL",
  "Netherlands": "NLD",
  "Netherlands Antilles": "ANT",
  "New Caledonia": "NCL",
  "New Zealand": "NZL",
  "Nicaragua": "NIC",
  "Niger": "NER",
  "Nigeria": "NGA",
  "Niue": "NIU",
  "Norfolk Island": "NFK",
  "North Korea": "PRK",
  "Northern Mariana Islands": "MNP",
  "Norway": "NOR",
  "Oman": "OMN",
  "Pakistan": "PAK",
  "Palau": "PLW",
  "Palestine": "PSE",
  "Panama": "PAN",
  "Papua New Guinea": "PNG",
  "Paraguay": "PRY",
  "Peru": "PER",
  "Philippines": "PHL",
  "Poland": "POL",
  "Portugal": "PRT",
  "Puerto Rico": "PRI",
  "Qatar": "QAT",
  "Congo": "COG",
  "Réunion": "REU",
  "Romania": "ROU",
  "Russia": "RUS",
  "Rwanda": "RWA",
  "Saint Barthélemy": "BLM",
  "Saint Helena": "SHN",
  "Saint Kitts and Nevis": "KNA",
  "Saint Martin": "MAF",
  "Saint Pierre and Miquelon": "SPM",
  "Saint Vincent and the Grenadines": "VCT",
  "Samoa": "WSM",
  "San Marino": "SMR",
  "São Tomé and Príncipe": "STP",
  "Saudi Arabia": "SAU",
  "Senegal": "SEN",
  "Serbia": "SRB",
  "Seychelles": "SYC",
  "Sierra Leone": "SLE",
  "Singapore": "SGP",
  "Sint Maarten (Dutch part)": "SXM",
  "Slovakia": "SVK",
  "Slovenia": "SVN",
  "Solomon Islands": "SLB",
  "Somalia": "SOM",
  "South Africa": "ZAF",
  "South Korea": "KOR",
  "South Sudan": "SSD",
  "Spain": "ESP",
  "Sri Lanka": "LKA",
  "Saint Lucia": "LCA",
  "Sudan": "SDN",
  "Suriname": "SUR",
  "Swaziland": "SWZ",
  "Sweden": "SWE",
  "Switzerland": "CHE",
  "Syrian Arab Republic": "SYR",
  "Taiwan": "TWN",
  "Tajikistan": "TJK",
  "Tanzania": "TZA",
  "Thailand": "THA",
  "Bahamas": "BHS",
  "Gambia": "GMB",
  "Timor-Leste": "TLS",
  "Togo": "TGO",
  "Tokelau": "TKL",
  "Tonga": "TON",
  "Trinidad and Tobago": "TTO",
  "Tunisia": "TUN",
  "Turkey": "TUR",
  "Turkmenistan": "TKM",
  "Turks and Caicos Islands": "TCA",
  "Tuvalu": "TUV",
  "Uganda": "UGA",
  "Ukraine": "UKR",
  "United Arab Emirates": "ARE",
  "United Kingdom": "GBR",
  "United States": "USA",
  "Uruguay": "URY",
  "U.S. Virgin Islands": "VIR",
  "Uzbekistan": "UZB",
  "Vanuatu": "VUT",
  "Vatican City": "VAT",
  "Venezuela": "VEN",
  "Vietnam": "VNM",
  "Wallis and Futuna": "WLF",
  "Yemen": "YEM",
  "Zambia": "ZMB",
  "Zimbabwe": "ZWE"
}